import type { NextConfig } from "next";
import oldSiteRedirects from "./src/seo/redirects.json";

const nextConfig: NextConfig = {
  // Lets a test build (NEXT_DIST_DIR=.next-test) run while `next dev` keeps using .next —
  // sharing one folder crashes the dev server.
  distDir: process.env.NEXT_DIST_DIR || ".next",
  // Trailing slashes are stripped in src/proxy.ts, after the old-site 301 map had its chance.
  skipTrailingSlashRedirect: true,
  images: {
    // Every photo is served as AVIF (smallest), WebP to browsers without AVIF, whatever format was
    // uploaded (JPG, PNG, AVIF, WebP). Converted once per size and cached.
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    // YouTube thumbnails and Instagram posts (Social Media), product photos from the feed.
    // (object form without `search`, so Instagram's signed query strings are allowed)
    remotePatterns: [
      new URL("https://i.ytimg.com/vi/**"),
      { protocol: "https", hostname: "**.cdninstagram.com", pathname: "/**" },
      new URL("https://thermosilesia.pl/assets/**"),
    ],
  },
  async redirects() {
    // Temporary: later replaced by browser-language detection.
    return [
      { source: "/", destination: "/pl", permanent: false },
      // 301s from the old rotenso.com addresses (products per the SEO sheet, categories, tags,
      // pages) — generated by `npm run seo:redirects`, see docs/seo/mapa-adresow.csv.
      // Old URLs end with "/": both forms redirect in one hop (no chain via the slash removal).
      ...oldSiteRedirects.flatMap((r) => [
        { ...r, permanent: true },
        { ...r, source: `${r.source}/`, permanent: true },
      ]),
    ];
  },
};

export default nextConfig;
